development:
  adapter: postgresql
  database: db/bikedb_development
  pool: 5
  timeout: 5000
  username:
  password:

test:
  adapter: postgresql
  database: db/bikedb_test
  pool: 5
  timeout: 5000
  username:
  password:

production:
  adapter: postgresql
  database: db/bikedb_production
  pool: 5
  timeout: 5000
  username:
  password:
